/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SendersParisRouteImport } from './routes/senders/paris'
import { Route as SendersNantesRouteImport } from './routes/senders/nantes'
import { Route as ReceiversOperatorRouteImport } from './routes/receivers/operator'
import { Route as ReceiversObsParisRouteImport } from './routes/receivers/obs-paris'
import { Route as ReceiversObsNantesRouteImport } from './routes/receivers/obs-nantes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SendersParisRoute = SendersParisRouteImport.update({
  id: '/senders/paris',
  path: '/senders/paris',
  getParentRoute: () => rootRouteImport,
} as any)
const SendersNantesRoute = SendersNantesRouteImport.update({
  id: '/senders/nantes',
  path: '/senders/nantes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiversOperatorRoute = ReceiversOperatorRouteImport.update({
  id: '/receivers/operator',
  path: '/receivers/operator',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiversObsParisRoute = ReceiversObsParisRouteImport.update({
  id: '/receivers/obs-paris',
  path: '/receivers/obs-paris',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiversObsNantesRoute = ReceiversObsNantesRouteImport.update({
  id: '/receivers/obs-nantes',
  path: '/receivers/obs-nantes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/receivers/obs-nantes': typeof ReceiversObsNantesRoute
  '/receivers/obs-paris': typeof ReceiversObsParisRoute
  '/receivers/operator': typeof ReceiversOperatorRoute
  '/senders/nantes': typeof SendersNantesRoute
  '/senders/paris': typeof SendersParisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/receivers/obs-nantes': typeof ReceiversObsNantesRoute
  '/receivers/obs-paris': typeof ReceiversObsParisRoute
  '/receivers/operator': typeof ReceiversOperatorRoute
  '/senders/nantes': typeof SendersNantesRoute
  '/senders/paris': typeof SendersParisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/receivers/obs-nantes': typeof ReceiversObsNantesRoute
  '/receivers/obs-paris': typeof ReceiversObsParisRoute
  '/receivers/operator': typeof ReceiversOperatorRoute
  '/senders/nantes': typeof SendersNantesRoute
  '/senders/paris': typeof SendersParisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/receivers/obs-nantes'
    | '/receivers/obs-paris'
    | '/receivers/operator'
    | '/senders/nantes'
    | '/senders/paris'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/receivers/obs-nantes'
    | '/receivers/obs-paris'
    | '/receivers/operator'
    | '/senders/nantes'
    | '/senders/paris'
  id:
    | '__root__'
    | '/'
    | '/receivers/obs-nantes'
    | '/receivers/obs-paris'
    | '/receivers/operator'
    | '/senders/nantes'
    | '/senders/paris'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReceiversObsNantesRoute: typeof ReceiversObsNantesRoute
  ReceiversObsParisRoute: typeof ReceiversObsParisRoute
  ReceiversOperatorRoute: typeof ReceiversOperatorRoute
  SendersNantesRoute: typeof SendersNantesRoute
  SendersParisRoute: typeof SendersParisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senders/paris': {
      id: '/senders/paris'
      path: '/senders/paris'
      fullPath: '/senders/paris'
      preLoaderRoute: typeof SendersParisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/senders/nantes': {
      id: '/senders/nantes'
      path: '/senders/nantes'
      fullPath: '/senders/nantes'
      preLoaderRoute: typeof SendersNantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivers/operator': {
      id: '/receivers/operator'
      path: '/receivers/operator'
      fullPath: '/receivers/operator'
      preLoaderRoute: typeof ReceiversOperatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivers/obs-paris': {
      id: '/receivers/obs-paris'
      path: '/receivers/obs-paris'
      fullPath: '/receivers/obs-paris'
      preLoaderRoute: typeof ReceiversObsParisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receivers/obs-nantes': {
      id: '/receivers/obs-nantes'
      path: '/receivers/obs-nantes'
      fullPath: '/receivers/obs-nantes'
      preLoaderRoute: typeof ReceiversObsNantesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReceiversObsNantesRoute: ReceiversObsNantesRoute,
  ReceiversObsParisRoute: ReceiversObsParisRoute,
  ReceiversOperatorRoute: ReceiversOperatorRoute,
  SendersNantesRoute: SendersNantesRoute,
  SendersParisRoute: SendersParisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
